### ISSUE TITLE
Example won't build without dynamic likers installed

### ISSUE THREAD

**Issue by SpectralPixel** [splashdust/bevy_voxel_world#35]
Just tried to run the `noise_terrain` example on a fresh system install, and it didn't work out-of-the-box until I installed the dynamic linkers from [bevy's quick start guide](https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional). It might be better if it worked without these assumptions...

Here's the error I encountered:
```
$ cargo run --example noise_terrain --features="noise"
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.153
   Compiling serde v1.0.196
   Compiling once_cell v1.19.0
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling pin-project-lite v0.2.13
   Compiling equivalent v1.0.1
   Compiling thiserror v1.0.61
   Compiling crossbeam-utils v0.8.16
   Compiling zerocopy v0.7.32
   Compiling hashbrown v0.14.2
   Compiling toml_datetime v0.6.5
   Compiling allocator-api2 v0.2.16
   Compiling tracing-core v0.1.32
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `serde` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `crossbeam-utils` (build script) due to 1 previous error
error: could not compile `proc-macro2` (build script) due to 1 previous error
error: could not compile `thiserror` (build script) due to 1 previous error
error: could not compile `libc` (build script) due to 1 previous error
```

**Comment by splashdust** [comment]
I don't think this has anything to do with this library, or bevy for that matter. You need a linker installed and configured to compile and run any program, and Cargo uses cc by default.

I'm not sure there's anything I can do in this project to help with this, so I'm closing the issue, but feel free to reopen if you have suggestions. Either way, thanks for opening an issue!
