### ISSUE TITLE
Vertex Shader Lightning Issue

### ISSUE THREAD

**Issue by seitenca** [splashdust/bevy_voxel_world#45]
Hi @splashdust,

Im using a [pixelation effect](https://github.com/rust-adventure/bevy_plugin_pixelate/blob/main/src/pixelating_plugin.rs) and I’m encountering an issue with the vertex shader [voxel_texture.wgsl](https://github.com/splashdust/bevy_voxel_world/blob/main/src/shaders/voxel_texture.wgsl). As you can see, when using the default vertex shader, the lighting works correctly, but since tex_idx is not passed, prevents from properly handling the texture, and with the custom vertex shader, its the contrary.

Even if I disable/remove the shader to pixelate the shadows the issue persist.

What do you think its causing the issue?

Btw great plugin :)

Thanks!!

![image](https://github.com/user-attachments/assets/1a4cba78-60d4-4fe8-ae8c-5877147233c2)

**Comment by splashdust** [comment]
Hey @seitenca, not sure what's going on here, but if you use a [custom material](https://github.com/splashdust/bevy_voxel_world/blob/main/examples/custom_material.rs) you can configure both vertex and fragment shaders, as well as the vertex buffer layout. If it works with [Bevy's standard vertex shader](https://github.com/bevyengine/bevy/blob/main/crates/bevy_pbr/src/render/mesh.wgsl), you could try copying that from Bevy's Github repo and just add the tex_idx forwarding to it.

If you think it is a bug in `bevy_voxel_world`, see if you can set up a minimal reproducible example.

**Comment by splashdust** [comment]
If you need the extra set of UVs, then yes. I'm planning to make the meshing customisable, but haven't gotten around to it yet, so for now the only way to add vertex attributes would be to modify meshing.rs.

**Comment by splashdust** [comment]
Are you on macOS? Sounds similar to [this issue](https://github.com/bevyengine/bevy/issues/16588). UVs are texture coordinate data, it's not related to render passes. I don't know why, but for some reason Bevy's pbr prepass pipeline expects UVs at different shader locations than the normal pass.

I solved it in [voxel_material.rs](https://github.com/splashdust/bevy_voxel_world/blob/main/src/voxel_material.rs#L64) by just skipping specialisation for the prepass.

**Comment by splashdust** [comment]
Good to hear!

Neat looking game btw!
